version: "3.8"

services:
  zammad:
    image: ghcr.io/zammad/zammad:6.5.2
    restart: always
    environment:
      # App domain
      ZAMMAD_FQDN: zammad.coolify.nulll.xyz
      NGINX_SERVER_NAME: zammad.coolify.nulll.xyz
      NGINX_ENFORCE_SSL: "false"      # Coolify handles HTTPS
      ZAMMAD_HTTP_TYPE: "https"

      # Database
      POSTGRESQL_HOST: zammad-postgresql
      POSTGRESQL_USER: zammad
      POSTGRESQL_PASS: zammad
      POSTGRESQL_DB: zammad_production

      # Redis
      REDIS_URL: redis://zammad-redis:6379

      # Elasticsearch
      ELASTICSEARCH_ENABLED: "true"
      ELASTICSEARCH_HOST: zammad-elasticsearch
      ELASTICSEARCH_PORT: 9200

      TZ: Europe/Berlin
    volumes:
      - zammad-storage:/opt/zammad/storage
    depends_on:
      - zammad-postgresql
      - zammad-redis
      - zammad-elasticsearch
    expose:
      - "8080"   # Internal exposure only; Coolify handles public proxy

  zammad-postgresql:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: zammad
      POSTGRES_PASSWORD: zammad
      POSTGRES_DB: zammad_production
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  zammad-redis:
    image: redis:7.4.5-alpine
    restart: always
    volumes:
      - redis-data:/data

  zammad-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  zammad-storage:
  postgresql-data:
  redis-data:
  elasticsearch-data:
