version: "3.8"

services:
  zammad:
    image: ghcr.io/zammad/zammad:6.5.2
    restart: always
    environment:
      # domain
      ZAMMAD_FQDN: zammad.coolify.nulll.xyz
      NGINX_SERVER_NAME: zammad.coolify.nulll.xyz
      NGINX_ENFORCE_SSL: "false"     # Coolify will handle TLS
      ZAMMAD_HTTP_TYPE: "https"

      # database
      POSTGRESQL_HOST: zammad-postgresql
      POSTGRESQL_USER: zammad
      POSTGRESQL_PASS: zammad
      POSTGRESQL_DB: zammad_production
      POSTGRESQL_PORT: 5432

      # redis
      REDIS_URL: redis://zammad-redis:6379

      # elasticsearch
      ELASTICSEARCH_ENABLED: "true"
      ELASTICSEARCH_HOST: zammad-elasticsearch
      ELASTICSEARCH_PORT: 9200

      TZ: Europe/Berlin
    volumes:
      - zammad-storage:/opt/zammad/storage
    depends_on:
      - zammad-postgresql
      - zammad-redis
      - zammad-elasticsearch
      - zammad-memcached
    expose:
      - "8080"

  zammad-postgresql:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: zammad
      POSTGRES_PASSWORD: zammad
      POSTGRES_DB: zammad_production
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  zammad-redis:
    image: redis:7.4.5-alpine
    restart: always
    volumes:
      - redis-data:/data

  zammad-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.4
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  zammad-memcached:
    image: memcached:1.6.39-alpine
    command: memcached -m 256M
    restart: always

volumes:
  zammad-storage:
  postgresql-data:
  redis-data:
  elasticsearch-data:
